version: '3.1'

services:

  db:
    image: postgres
    container_name: simple-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "30003:5432"